baseURL = "https://jsontypedef.com/"
languageCode = "en-us"
title = "JSON Typedef · Schemas you can generate code from"

[markup.highlight]
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[params]
title = "JSON Type Definition"
description = "Schemas for JSON, optimized for code generation"
images = ["og_image.png"]
